#!/usr/bin/env python3
"""Add project-reviewed Chinese names for selected remaining weapon trees."""
from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "Sources/HunterDex/Resources"
DB = sqlite3.connect(RES / "mhgu.db")
DB.row_factory = sqlite3.Row
linked_path = RES / "linked-localization.json"
source_path = ROOT / "LINKED-LOCALIZATION-SOURCES.json"
linked = json.loads(linked_path.read_text())
sources = json.loads(source_path.read_text())
base = json.loads((RES / "localization.json").read_text())
zh = json.loads((RES / "zh.json").read_text())
known = {**base.get("items_by_id", {}), **linked.get("items_by_id", {})}

# Reviewed renderings for English weapon names in the unlocalized upgrade trees.
# Each entry maps the exact English name without its rank suffix to its Chinese name.
NAMES = {
    "Petrified Sword": "化石片手剑", "Scholarly Sword": "学者之剑", "Sophos Sword": "贤者之剑",
    "Obsidian Sword": "黑曜石片手剑", "Lustrous Cretecia": "光辉克雷特之剑", "Ethereal Cretecia": "空灵克雷特之剑",
    "Dios Edge": "碎龙刃", "Booming Barrage": "爆裂连击", "Thermostorm": "烈焰风暴",
    "Struxion Demolisher": "破坏者", "Struxion Annihilator": "歼灭者",
    "Hidden Edge": "隐秘之刃", "Frost Edge": "冰霜之刃", "Hi Frost Edge": "极寒之刃", "Permafrost Edge": "永冻之刃",
    "Velocidrome Bite": "蓝速龙王之咬", "Velocidrome Fang": "蓝速龙王之牙", "Velocidrome Fang Slash": "蓝速龙王裂牙斩",
    "Raven Blade": "乌鸦之刃", "Wolf Blade": "狼之刃", "Crow Blade": "黑鸦之刃",
    "Spiked Circle": "尖刺圆刃", "Paraspiked Circle": "麻痹尖刺圆刃", "Paraspiked Rondo": "麻痹尖刺圆舞刃",
    "Shura Fan": "修罗扇", "Dream Duke Shura": "梦境修罗公爵扇", "Dream Archduke Shura": "梦境修罗大公扇",
    "Champion's Sword": "勇者之剑", "Odyssey Blade": "奥德赛之刃", "Master Odyssey": "大师奥德赛之刃", "Agamemnon": "阿伽门农之刃",
    "Hunter's Dagger": "猎人匕首", "Assassin's Dagger": "暗杀者匕首", "Master's Dagger": "大师匕首",
    "Heavy Bang": "重击", "Master Bang": "大师重击", "Bang Bang": "双重重击",
    "Baumfäller": "伐木者", "Dendrotomy": "伐木之刃", "Plutocatena": "富饶之链",
    "Dual Carapace": "双甲壳刃", "Dual Scissors": "双剪刃", "Dual Crustacio": "双壳蟹刃",
    "Lava Pick": "熔岩镐", "Burly Beak": "强韧之喙", "Bruising Beak": "重击之喙",
    "Soldier's Dagger": "士兵匕首", "Commander's Dagger": "指挥官匕首", "Elite Dagger": "精英匕首",
    "Usurper's Firebolt": "掠夺者雷矢", "Princess Rapier": "公主细剑", "Queen Rapier": "女王细剑", "Empress Rapier": "女帝细剑",
    "Lunatic Rose": "疯狂玫瑰", "Lunatic Briar": "疯狂荆棘",
    "Khezu Razor": "奇怪龙剃刀", "Painful Razor": "痛苦剃刀", "Dread Razor": "恐惧剃刀",
    "Serpent Bite": "蛇咬", "Serpent Cleaver": "蛇斩", "Serpent Soul": "蛇魂",
    "Viper Bite": "毒蛇之咬", "Deathprize": "死亡奖赏", "Deathgrip": "死亡之握",
    "Hydra Bite": "九头蛇之咬", "Deadly Poison": "致命毒素", "Lethal Poison": "致死毒素",
    "Snake Bite": "蛇咬", "Snowy Cleaver": "雪原斩刀", "Asp Bite": "蝰蛇之咬",
    "Naab Sword": "纳布之剑", "Feral Fangs": "野性獠牙", "Insurgent Fangs": "叛逆獠牙",
    "Bone Kris": "骨制匕首", "Chief Kris": "酋长匕首", "King Kris": "王者匕首",
    "Djinn": "精灵之刃", "Blazing Falchion": "烈焰弯刀", "High Ifrit": "高等伊芙利特",
    "Corona": "日冕", "Daze Eye": "迷乱之眼", "Suncore": "太阳核心",
    "Golden Falchion": "黄金弯刀", "Golden Radius": "黄金光环", "Golden Riot": "黄金狂暴",
    "Bone Pick": "骨镐", "Osteon Pick": "骨质镐", "Spinal Pick": "脊骨镐",
    "Demonlord Mace": "魔王之锤", "Demonlord Bludgeon": "魔王棍", "Demonlord Crusher": "魔王碎击锤",
    "Weary Finsword": "疲惫鳍剑", "Sandman Finsword": "睡魔鳍剑", "Phobetor Finsword": "福柏托鳍剑",
    "Thunderbane": "雷霆克星", "Frightbane": "恐惧克星", "Indra": "因陀罗",
    "Ludroth's Nail": "水兽之钉", "Ludroth Gear": "水兽机刃", "Foaming Ludroth Gear": "泡沫水兽机刃",
    "Royal Claw": "王家之爪", "Royal Ludroth Claw": "皇家水兽之爪",
    "Panja Sedition": "爪掌叛乱", "Sedition Shredder": "叛乱撕裂者",
    "Gigas Club": "巨神棍", "Gigas Crusher": "巨神碎击棍", "Mighty Gigantreon": "强袭巨神棍",
    "Bone Tabar": "骨制战斧", "Ragdos Tabar": "拉格多斯战斧", "Bonebreaker Tabar": "碎骨战斧",
    "Sharkutter": "鲨鱼切割者", "Sharkgutter": "鲨鱼破坏者", "Sharkslitter": "鲨鱼裂刃",
    "Sharfin Sword": "鲨鳍剑", "Sharfinisher": "鲨鳍终结者", "Icy Akzar": "冰霜阿克扎尔",
    "Lagia Sword": "海龙剑", "High Lagia Sword": "高阶海龙剑", "Exlagia Sword": "超海龙剑",
    "Storm Sword": "风暴之剑", "Takemikazuchi": "建御雷神之剑", "Susanoo-no-Mikoto": "须佐之男之剑",
    "Poison Axe": "毒斧", "Poison Battleaxe": "毒战斧", "Strong Poison Battleaxe": "强毒战斧",
    "Brash Buddies": "粗野搭档", "Secta Nulo": "甲虫刃·零式", "Secta Unu": "甲虫刃·壹式", "Secta Du": "甲虫刃·贰式",
    "Secta Nulo (G)": "甲虫刃·零式（绿）", "Secta Unu (G)": "甲虫刃·壹式（绿）", "Secta Du (G)": "甲虫刃·贰式（绿）",
    "Secta Nulo (R)": "甲虫刃·零式（红）", "Secta Unu (R)": "甲虫刃·壹式（红）", "Secta Du (R)": "甲虫刃·贰式（红）",
    "Celestial Brand": "天界烙印", "Empyreal Brand": "苍穹烙印",
    "Dual Cross Brand": "双重交叉烙印", "Grand Dual Cross": "大交叉双重烙印",
    "Verdant Rapier": "翠绿细剑", "Lightning Rapier": "雷光细剑", "Astalos Rapier": "电龙细剑",
    "Colossus's Tusk": "巨像之牙", "Behemoth's Tusk": "贝希摩斯之牙",
    "Hana no Nagoriwo": "花之遗念", "Kurenawi Ougi": "红薙扇", "Kurenawi Kunpuu": "红薙薰风扇",
    "Burning Prominar": "燃烧普罗米纳", "Glinting Glavenus": "闪耀斩龙刃", "Glinting Glavenova": "闪耀斩龙新星",
    "Sucher-Ankh": "探索者安卡", "Jäger-Ankh": "猎人安卡", "Sieger-Ankh": "胜利者安卡",
    "Le Détecteur": "探测者", "La Vérité": "真理", "Le Limier": "追踪者",
    "Skeletal Blade": "骸骨之刃", "Aldebaran Horns": "毕宿五之角",
    "Astral Taurus": "星辰金牛", "Enraged Taurus": "狂怒金牛", "Wrathful Taurus": "暴怒金牛",
    "Akantor Duo": "霸龙双刃", "Akantor Coup": "霸龙斩击", "Akantor Purge": "霸龙解放",
    "Ukanlos Soul Hatchet": "崩龙魂斧", "Ukanlos Skyhatchet": "崩龙天斧", "Ukanlos Earth Hatchet": "崩龙地斧",
    "Alatreon Star": "煌黑龙之星", "Altheos Zodiarch": "煌黑龙黄道之王",
    "Heavenly Gale": "天穹疾风", "Heaven and Earth": "天地双刃",
    "Daora's Razor": "钢龙剃刀", "Daora's Maelstrom": "钢龙大漩涡",
    "Teostra's Spada": "炎王龙之剑", "Teostra's Emblem": "炎王龙徽记", "Teostra's Medal": "炎王龙勋章",
    "Tusk Gear": "獠牙齿轮", "Skull's Wrath": "骷髅之怒", "Chalcamine Sword": "查尔卡明之剑",
    "Black Sword": "黑之剑", "Chrono Sword": "时空之剑",
    "Yukumo Hatchet": "结云手斧", "Hot Spring Hatchet": "温泉手斧",
    "Moofah Sword": "毛芙剑", "Sleepy Moofah": "昏昏欲睡的毛芙剑", "Sound Asleep Moofah": "沉睡毛芙剑",
    "Legend's Blade": "传说之刃", "Chak Chak": "咔嚓剑", "Wagga Wagga": "哇嘎哇嘎剑", "Gimble Gyre": "旋转剑轮",
    "Floral Seif": "花之西夫", "Blooming Seif": "绽放西夫", "Garlanded Seif": "花冠西夫",
    "Ninja Sword": "忍者刀", "Hi Ninja Sword": "上忍刀", "Ninja Master Sword": "忍者大师刀",
    "Catspaw": "猫爪", "Catburglar": "猫盗贼", "Catlike Tread": "猫步",
    "Melynx Tool": "梅拉露工具", "Melynx Gadget": "梅拉露机关具", "Melynx Master": "梅拉露大师之具",
    "Black Belt Sword": "黑带之剑", "Shihan Sword": "师范之剑", "Grandmaster Sword": "宗师之剑",
    "Dreadqueen Rapier": "紫毒姬细剑", "Dreadqueen Rapier Rose": "紫毒姬玫瑰细剑", "Dreadqueen Rapierina": "紫毒姬女王细剑",
    "Nightfall Edge": "夜幕之刃", "Geode Mace": "晶洞大锤", "Crystalbeard Mace": "宝缠大锤", "Diamante Mace": "钻石大锤",
    "Hardened Edge": "淬炼之刃", "Deadeye Edge": "独眼之刃", "Tomb Edge": "墓冢之刃",
    "Dreadking Edge": "黑炎王之刃", "Firewaltz Edge": "烈焰华尔兹之刃",
    "Thunderlord Firebolt": "金雷公雷矢", "Grimclaw Barb": "荒钩爪棘刺",
    "Fiery Prominar": "烈焰普罗米纳", "Magma Hellblade": "熔岩地狱刃", "Magma Nova": "熔岩新星",
    "Inazuma Works": "雷光工坊", "Ikazuchi Works": "雷霆工坊", "Levindicator": "雷霆指示器",
    "CoroCoro Thunderbolt": "滚滚雷矢", "Rolling Thunderbolt": "滚雷矢",
    "Master Sword": "大师之剑", "Master Sword G": "大师之剑G",
    "Dragonstar Alcor": "龙星阿尔科", "Magnastar Akri": "巨星阿克里",
    "Zephra Rapier": "泽弗拉细剑", "Zephra Espada": "泽弗拉剑", "Zilvolt Espada": "雷伏特剑",
    "Tokaede": "十楓剑", "Sanitsurau": "散逸剑", "Elderfrost Opposer": "银岭抗争者",
    "Massacre Club": "屠杀棍", "Massacre Bludgeon": "屠杀重棍", "Kristatu": "克里斯塔图",
    "Razor Render": "剃刃者", "Careless Render": "无情剃刃者", "Rustrazor Render": "铠裂剃刃者",
    "Cloaked Fan": "隐匿之扇", "Cloaked Schlaf": "隐匿之眠", "Cloaked Dämmerschlaf": "隐匿的暮眠",
    "Lightbreak Ray": "碎光射线", "Lightbreak Beam": "碎光光束",
    "Verstecken/Chercher": "藏与寻", "Entkommen/Trouver": "逃脱与寻获", "Lügen/Vérité": "谎言与真相",
    "Flame Syphos": "烈焰西福斯", "Black Doom Flame": "黑色灾厄之焰", "Red Divine Flame": "赤红神焰",
    "Studded Club": "铆钉棍", "Spiked Bat": "尖刺球棒", "Barbarian Terror": "野蛮恐惧",
    "Icicle Spike": "冰柱尖刺", "Nardebosche": "纳德博施", "Never Event": "永不发生",
    "Cryo Cross": "冰霜十字", "Icestorm Cross": "冰暴十字", "Glacio Cross": "冰川十字",
    "Carapace Mace": "甲壳大锤", "Barroth Club": "土砂龙棍", "Pneumatic Drillblade": "气动钻刃",
    "Scaly Sword": "鳞片之剑", "Nerskiller": "影蜘蛛猎杀者", "Shadow Nerwrithe": "影蜘蛛缠刃",
    "Bloodscale Sword": "血鳞之剑", "Bloodsquama Sword": "血鳞剑", "Bloodslaughter": "血腥屠杀者",
    "Platinum Dawn": "白金黎明", "Annular Sol": "日环", "Daybreak Sun": "破晓之日",
    "Binding Blade": "束缚之刃", "Great Kris": "大匕首", "Bloodsucker": "吸血者",
    "Drome Rush Dagger": "速龙突袭匕首", "Great Stabberdag": "强袭刺杀匕首", "Azure Drome Tooth": "苍蓝速龙之牙",
    "Research Sword": "研究之剑", "Authority Pathfinder": "权威开拓者",
    "Insignia Dagger": "徽记匕首", "Ravilian Insignia": "拉维利亚徽记",
    "Elder Sword": "长老之剑", "Sage Sword": "贤者之剑", "Philosopher Sword": "哲学家之剑",
    "Falchion": "弯刀", "Exalted Falchion": "尊贵弯刀", "Illustrious Falchion": "卓越弯刀",
    "Crimson Bowgun": "绯红弩枪", "Crimson Cannon": "绯红炮", "Crimson Crasher": "绯红粉碎者",
    "Eeostopen Burst": "速龙爆发弩", "Eeostopen Cannon": "速龙火炮", "Eeostopen Avalanche": "速龙雪崩炮",
    "Stonefist Buster": "矛碎破坏炮", "Ebon Stonefist Buster": "黑曜矛碎破坏炮", "Stonefist Blaster": "矛碎爆破炮",
    "Grobo Shot": "格罗博射击弩", "Grobo Barzeta": "格罗博巴泽塔", "Grobo Shot Diamante": "格罗博钻石射击弩",
    "Rudra's Howl": "楼陀罗咆哮", "Grimclaw Cannon": "荒钩爪重炮", "Grimclaw Howl": "荒钩爪咆哮炮",
    "Verrat/Foi": "谎言／信仰", "Sicherheit/Risque": "安全／风险", "Ursprung/Mort": "起源／死亡",
    "Loyal Thunder": "忠诚雷霆", "Oppressor's Wedge": "压迫者楔炮", "Orcus Quarcus": "奥库斯夸库斯",
    "Beschwörung/Oracle": "召唤／神谕", "Vergebung/Peine": "宽恕／苦痛", "Fäulnis/Vertu": "腐朽／美德",
    "Übel/Equité": "邪恶／公正", "Verzeihung/Jugement": "宽恕／审判", "Chaos/Loi": "混沌／法则",
    "Gríðr's Landforger": "格里兹大地锻造者", "Rathsplicer": "火龙拼接刃",
    "Körper/Esprit": "肉体／精神", "Fleisch/Ame": "血肉／灵魂", "Frevel/Sursis": "亵渎／宽限",
    "Ruhe/Tyrannie": "平静／暴政", "Demut/Orgueil": "谦逊／傲慢", "Mauer/Guerre": "城墙／战争",
    "Warflare Annihilator": "战焰歼灭者", "Sacred Bow": "圣弓", "Sacred Bow G": "圣弓G", "Perennial Winter": "永恒寒冬",
    "Gewinn/Perte": "得／失", "Verzweiflung/Désir": "绝望／渴望", "Auftauchen/Disparition": "显现／消逝",
    "Glacial Gorgoneion": "冰川蛇发女妖盾", "Dreadqueen Daggers": "紫毒姬双匕首",
    "Apostel/Sorcière": "使徒／女巫", "Inferno/Paradis": "地狱／天堂", "Shangri-La/Hades": "香格里拉／冥府",
    "Petrified Horn": "化石狩猎笛", "Scholarly Horn": "学者狩猎笛", "Sophos Horn": "贤者狩猎笛",
    "Obsidian Horn": "黑曜石狩猎笛", "Relic Horn": "遗物狩猎笛", "Ethereal Horn": "空灵狩猎笛",
    "Vadya Muse": "乐神缪斯", "Allysyl Muse": "阿莉西尔缪斯", "Allysyl Rebel": "阿莉西尔叛逆者",
    "Maqam Sedition": "叛乱玛卡姆", "Sedition Caller": "叛乱号角",
    "Droth Drone": "水兽无人笛", "Droth Roar": "水兽咆哮笛", "Echoing Droth Roar": "回响水兽咆哮笛",
    "Kut-Ku's Song": "大怪鸟之歌", "Kut-Ku Cantabile": "大怪鸟如歌", "Kut-Ku Tempestoso": "大怪鸟暴风曲",
    "Poisoned Capri": "毒化卡普里", "Crazed Melody": "狂乱旋律", "Lunatic Melody": "疯狂旋律",
    "Larinoth Ocarina": "拉里诺斯陶笛", "Resonant Ocarina": "共鸣陶笛", "Harmonious Ocarina": "和谐陶笛",
    "Iron Horn": "铁制狩猎笛", "Wind Horn": "风之狩猎笛", "Grand Horn": "宏伟狩猎笛",
    "Agnakdion": "炎戈迪翁笛", "Brandoneon": "布兰多尼翁笛", "Scaldertina": "斯卡尔德蒂娜笛",
    "Valkyrie Chordmaker": "女武神弦乐器", "Queen's Chordmaker": "女王弦乐器", "Queen's Harmonium": "女王簧风琴",
    "Gold Chordmaker": "黄金弦乐器", "Lunar Chordmaker": "月之弦乐器", "Amas Chordmaker": "阿玛斯弦乐器",
    "Metal Bagpipe": "金属风笛", "Great Bagpipe": "大型风笛", "Energetic Bagpipe": "活力风笛",
    "Heavy Bagpipe": "重型风笛", "Fortissimo": "极强音", "Rinforzato": "加固强音",
    "Lagia Horn": "海龙之笛", "Lagia Thunderpeal": "海龙雷鸣笛", "Lagia Cannonade": "海龙齐射笛",
    "Hidden Harmonic": "隐秘和声笛", "Poli'ahu Pipe": "波利阿胡之笛", "Phenomenal Phlute": "非凡长笛", "Phantasmagorical Phlute": "奇幻长笛",
    "Snarfonix": "斯纳弗尼克斯笛", "Soldier's Snarfonica": "士兵斯纳弗尼克笛",
    "Sonic Glass": "音波玻璃笛", "Glass Queen": "玻璃女王笛", "Glass Monarch": "玻璃君主笛",
    "Bone Horn": "骨制狩猎笛", "Hardened Bone Horn": "硬化骨笛", "Heavy Bone Horn": "重型骨笛",
    "Hunter's Horn": "猎人之笛", "Native's Horn": "原住民之笛", "Primal Horn": "原初之笛",
    "Dios Bell": "碎龙之铃", "Napalm Bell": "燃烧弹之铃", "Firestorm Bell": "烈焰风暴之铃",
    "Timbral Demolisher": "音色毁灭者", "Timbral Annihilator": "音色歼灭者",
    "Danger Call": "危险呼号", "Dangerous Haar": "危险之发", "Baleful Haar": "凶煞之发",
    "Hazardous Call": "危机呼号", "Parahazard Call": "麻痹危机呼号", "Para Calamity": "麻痹灾厄",
    "Velociprey Balloon": "蓝速龙气球笛", "Velocidrome Balloon": "蓝速龙王气球笛", "Velocidrome Horn": "蓝速龙王之笛", "Giaprey Balloon": "白速龙气球笛",
    "Khezu Horn": "奇怪龙之笛", "Khezu Flute": "奇怪龙长笛", "Khezu Keen": "奇怪龙锐音笛",
    "Bull Grunt": "蛮牛怒吼笛", "Wild Grunt": "野性怒吼笛", "Barbarian Grunt": "蛮族怒吼笛",
    "Zurogong Primo": "祖罗贡一型", "Zurogong Secundo": "祖罗贡二型", "Zurogong Tertio": "祖罗贡三型",
    "Kecha Whappa": "奇猿狐哇啪笛", "Kechachacha Whappa": "奇猿狐恰恰哇啪笛", "Kechawacky Whappa": "奇猿狐狂乱哇啪笛",
    "Kecha Thumpa": "奇猿狐重击笛", "Kecha Clanga": "奇猿狐铿锵笛", "Kecha Clanvira": "奇猿狐克兰维拉笛",
    "Striped Dragonga": "条纹飞龙笛", "Brazengaita": "布雷森盖塔笛", "Gigas Gaita": "巨神盖塔笛", "Archgigas Gaita": "大巨神盖塔笛",
    "Vermillion Frog": "朱红蛙笛", "Temple Block": "寺庙木鱼", "Mountain Echo": "山之回响", "Peak Performance": "巅峰演奏",
    "Shell Castanet": "甲壳响板", "Colored Castanet": "彩色响板", "Twinshell Castanet": "双壳响板",
    "Vicello Nulo": "维切洛零式", "Vicello Unu": "维切洛壹式", "Vicello Du": "维切洛贰式",
    "Vicello Nulo (G)": "维切洛零式（绿）", "Vicello Unu (G)": "维切洛壹式（绿）", "Vicello Du (G)": "维切洛贰式（绿）",
    "Vicello Nulo (R)": "维切洛零式（红）", "Vicello Unu (R)": "维切洛壹式（红）", "Vicello Du (R)": "维切洛贰式（红）",
    "Vicello Nulo (W)": "维切洛零式（白）", "Vicello Unu (W)": "维切洛壹式（白）", "Vicello Du (W)": "维切洛贰式（白）",
    "Usurper's Growl": "掠夺者咆哮笛", "Fool's Harp": "愚者竖琴", "Jester's Harp": "弄臣竖琴", "Trickster's Harp": "诡计师竖琴",
    "Lava Alphorn": "熔岩阿尔卑斯号角", "Volcano Alphorn": "火山阿尔卑斯号角", "Magma Alphorn": "岩浆阿尔卑斯号角",
    "Raven Shamisen": "乌鸦三味线", "Wolf Shamisen": "狼三味线", "Crow Shamisen": "渡鸦三味线",
    "Vile Shamisen": "邪恶三味线", "Garuga Shamisen": "黑狼鸟三味线",
    "Dodotto Horn": "多多托之笛", "White Dodotto Horn": "白色多多托之笛", "Grand Dodotto Horn": "宏伟多多托之笛",
    "Emerald Flap": "翡翠振翅笛", "Lightning Flap": "雷光振翅笛", "Grünlicht Flap": "绿光振翅笛",
    "Colossus's Koto": "巨像古筝", "Behemoth's Koto": "贝希摩斯古筝",
    "Poetic Bell": "诗歌之铃", "Summoning Bell": "召唤之铃", "Sublime Bell": "庄严之铃",
    "Hell Horn": "地狱之笛", "Glavenus Horn": "斩龙之笛", "Glavenus Hornova": "斩龙新星笛",
    "Kummerklang": "悲叹之音", "Gramklang": "愤怒之音", "Trauerklang": "哀悼之音",
    "La Sépulture": "墓葬之笛", "La Joie": "欢愉之笛", "Le Grégorien": "格里高利圣咏笛",
    "Blessed Ocarina": "受祝福的陶笛", "Cursed Ocarina": "受诅咒的陶笛", "Genie's Ocarina": "精灵陶笛",
    "Teostra's Tiple": "炎王龙小吉他", "Teostra's Orphée": "炎王龙俄耳甫斯琴", "Teostra's Musica": "炎王龙乐器",
    "Skeletal Melody": "骸骨旋律", "Spica Melody": "角宿一旋律", "Polaris Wraith": "北极星幽魂", "Cosmic Wraith": "宇宙幽魂", "Lodestar Wraith": "指路星幽魂",
    "Akantor Horn": "霸龙之笛", "Akantor Dark Melody": "霸龙暗黑旋律", "Akantor Dirge": "霸龙哀歌",
    "Ukanlos Horned Flute": "崩龙角笛", "Ukanlos Skysinger": "崩龙天歌笛", "Ukanlos Decaysinger": "崩龙衰灭笛",
    "Harvest Lute": "丰收鲁特琴", "Equinox Lute": "昼夜平分鲁特琴", "Avenir's Music Box": "未来音乐盒", "Eternal Music Box": "永恒音乐盒", "Perpetual Music Box": "不朽音乐盒",
    "Daora's Taus": "钢龙陶斯琴", "Daora's Baphophone": "钢龙巴风琴", "Daora's Diabassoon": "钢龙低音管",
    "Black Lute": "黑色鲁特琴", "Onyx Lute": "缟玛瑙鲁特琴", "Fatalis Menace": "黑龙威胁",
    "Yukumo Horn": "结云之笛", "Hot Spring Horn": "温泉之笛", "Bherna Chime": "贝尔纳钟笛", "Blissful Chime": "幸福钟笛", "Divine Carillon": "神圣钟琴",
    "Airship Horn": "飞空艇之笛", "Grand Airship Horn": "大型飞空艇之笛", "Resonant Airship Horn": "共鸣飞空艇之笛",
    "Licht/Ombre": "光明／暗影", "Düster/Éclat": "黑暗／光辉", "Anfang/Fin": "起始／终焉",
    "Eldora Closure": "埃尔多拉闭幕", "Treasured Fedda": "珍宝菲达", "Lost Ys": "失落伊斯",
    "Inscribed Ausir": "铭文奥西尔", "Unnefer": "欧内费尔", "Royal Lobstrosity": "皇家巨虾钳",
    "Diamgolgo's Phantasm": "迪安戈尔戈的幻象", "Old Fatalis Ruiner": "祖龙毁灭者",
    "Grinsen/Froncement": "欢笑／愁容", "Segen/Malédiction": "祝福／诅咒", "Vergehen/Naissance": "消逝／新生",
    "Brutal Tusk": "残暴獠牙", "Ogre Tusk": "鬼怪獠牙", "Immaculate Soul": "纯洁之魂",
    "Draconic Rim": "龙之边缘", "Sealed Dragonlance": "封印龙枪", "Lightbreak Pyre": "碎光火葬枪",
    "Ehrlich/Faux": "真实／虚假", "Beschützer/Méchant": "守护者／恶人", "Luzifer/Sage": "路西法／智者",
    "Handmade Frog": "手制青蛙笛", "Handcrafted Frog": "精制青蛙笛", "Artisanal Frog": "匠造青蛙笛",
    "Magia Charm": "魔法护符笛", "Magia Charmbell": "魔法护符铃笛", "Aria Rhota": "旋律罗塔",
    "Swell Shell": "膨胀贝壳笛", "Vertex Shell": "顶点贝壳笛", "Turban Shell": "宝螺壳笛",
    "Azumand Wind": "阿祖曼之风", "Fern Fan": "蕨叶扇笛", "Fiddlehead Fan": "拳头蕨扇笛",
    "Poison Fungasax": "毒菌萨克斯", "Toxic Fungasax": "剧毒菌萨克斯", "Mycotoxic Fungasax": "真菌剧毒萨克斯",
    "Cornupion": "角虫笛", "Webbed Cornupion": "网翅角虫笛", "Gossamer Cornupion": "薄纱角虫笛",
    "Crimson Horn": "绯红之笛", "Crimson Great Horn": "绯红大笛", "Crimson Superb Horn": "绯红绝笛",
    "Royal Horn": "王家之笛", "Dreadqueen Horn": "紫毒姬之笛", "Dreadqueen Thornflute": "紫毒姬棘笛",
    "Nightfall Horn": "夜幕之笛", "Geode Horn": "晶洞之笛", "Crystalbeard Horn": "宝缠之笛", "Diamante Horn": "钻石之笛",
    "Hardened Horn": "硬化之笛", "Deadeye Horn": "独眼之笛", "Tomb Horn": "墓冢之笛",
    "Dreadking Horn": "黑炎王之笛", "Firewaltz Horn": "烈焰华尔兹之笛",
    "Raiden Horn": "雷电之笛", "Seize Horn": "夺取之笛", "Magma Horn": "岩浆之笛",
    "Hellblade Horn": "烬灭刃之笛", "Glavepyre Horn": "斩龙火葬笛",
    "Blitz Works": "雷霆工坊", "Giga Blitz Works": "巨型雷霆工坊",
    "Megaphone": "扩音器", "Gigaphone": "巨型扩音器", "Teraphone": "超巨型扩音器",
    "Inscribed Bastet": "铭文巴斯特", "Menat Sekhem": "门纳特权杖",
    "Dragonstar Halm": "龙星哈姆", "Magnastar Edon": "巨星埃顿",
    "Zephra Glide": "泽弗拉滑翔笛", "Zephra Wingbeat": "泽弗拉振翅笛", "Zilvolt Glide": "泽尔伏特滑翔笛",
    "Madderdance": "疯狂之舞", "Dans Obscura": "暗影之舞", "Elderfrost Singer": "银岭歌者", "Elderfrost Mythmaker": "银岭神话缔造者",
    "Razor Castanet": "剃刃响板", "Lunatic Castanet": "疯狂响板", "Rustrazor Castanet": "铠裂响板",
    "Cloaked Lyre": "隐匿竖琴", "Cloaked Traum": "隐匿之梦", "Cloaked Albtraum": "隐匿噩梦",
    "Fatalis Firelied": "黑龙烈焰之歌", "Fatalis Firelute": "黑龙烈焰鲁特琴", "Fatalis Flame Aria": "黑龙火焰咏叹调",
    "Old Fatalis Lied": "祖龙之歌", "Old Fatalis Lute": "祖龙鲁特琴", "Old Fatalis Aria": "祖龙咏叹调",
    "Lightbreak Seismograph": "碎光地震仪", "Lightbreak Claque": "碎光响板",
    "Lache/Sanglot": "欢笑／啜泣", "Freude/Tristesse": "喜悦／悲伤", "Grimm/Joie": "阴郁／欢欣",
    "Basarios Rock": "岩龙岩石笛", "Basarios Rock Mk.II": "岩龙岩石笛II型", "Titan's Rock": "泰坦之岩",
    "Volcanic Rock": "火山岩笛", "Volcanic Gig": "火山巨岩笛", "Conflagrig": "大火灾笛",
    "War Bongo": "战争邦戈鼓", "War Conga": "战争刚果鼓",
    "Bariguiro": "巴里吉罗笛", "Algiguiro": "阿尔吉吉罗笛", "Frigiguiro": "弗里吉吉罗笛",
    "Sandpipe": "沙之笛", "Sandcrier": "沙之呐喊笛", "Sandscreecher": "沙之尖啸笛",
    "Sandsinger": "沙之歌者", "Sandsoother": "沙之抚慰者", "Sandrigal": "沙之里加尔笛",
    "War Drum": "战鼓", "Rout Drum": "溃敌战鼓", "Victory Drum": "胜利战鼓",
    "Glass Royale": "皇家玻璃笛", "Memento Mosca": "飞虫纪念笛", "Mosca Select": "精选飞虫笛", "Premium Suite": "高级套曲",
    "Research Horn": "研究之笛", "Authority Trumpeteer": "权威号手", "Elder Horn": "长老之笛",
    "Sage Horn": "贤者之笛", "Philosopher Horn": "哲学家之笛",
    "List/Confiance": "狡黠／信任", "Bruch/Logique": "破坏／逻辑", "Wehmut/Merveille": "忧伤／奇迹",
    "Elends/Essor": "困苦／腾飞", "Gefunden/Ruine": "寻获／废墟", "Friede/Désastre": "和平／灾难",
}

added = 0
for row in DB.execute("SELECT i._id, i.name FROM items i JOIN weapons w USING(_id) ORDER BY i._id"):
    item_id = str(row["_id"])
    if re.search(r"[\u3400-\u9fff]", known.get(item_id, zh.get("items", {}).get(row["name"], ""))):
        continue
    match = re.fullmatch(r"(.+?)\s+(\d+)", row["name"])
    if not match or match.group(1) not in NAMES:
        continue
    translated = f"{NAMES[match.group(1)]} Lv.{match.group(2)}"
    linked.setdefault("items_by_id", {})[item_id] = translated
    sources.setdefault("items", {})[item_id] = [{
        "name": translated,
        "method": "project-reviewed Chinese rendering of the exact English weapon name and rank",
        "english": row["name"],
    }]
    added += 1

linked_path.write_text(json.dumps(linked, ensure_ascii=False, indent=2) + "\n")
source_path.write_text(json.dumps(sources, ensure_ascii=False, indent=2) + "\n")
print(f"Imported {added} project-reviewed weapon names.")
