#!/usr/bin/env python3
"""Add reviewed Chinese names for remaining MHGU item records."""
import json
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / 'Sources/HunterDex/Resources'
db = sqlite3.connect(RES / 'mhgu.db')
linked_path = RES / 'linked-localization.json'
sources_path = ROOT / 'LINKED-LOCALIZATION-SOURCES.json'
linked = json.loads(linked_path.read_text())
sources = json.loads(sources_path.read_text())

# Names below are direct translations of database item names, using the
# project's Monster Hunter terminology. Keep the mapping keyed by the complete
# English name so rarity variants and similar parts cannot collapse together.
TRANSLATIONS = {
    'Butterfly Beetle': '大锹凤蝶',
    'Toxic Kumori': '毒蜘蛛蝎',
    'Large Toxic Kumori': '猛毒蜘蛛蝎',
    'Unknown Skull': '谜之头骨',
    'Huge Unknown Skull': '巨大谜之头骨',
    'Sharp Claw': '尖爪',
    'Ioprey Fang': '红速龙的大牙',
    'Zamtrios Hide+': '变形冰鲨的上皮',
    'Zamtrios Piel': '变形冰鲨的皮',
    'Zamtrios Scale+': '变形冰鲨的上鳞',
    'Zamtrios Shard': '变形冰鲨的厚鳞',
    'Zamtrios Fin+': '变形冰鲨的上鳍',
    'Zamtrios Grandfin': '变形冰鲨的特上鳍',
    'Zamtrios Sawtooth': '变形冰鲨的锯齿',
    'Zamtrios Sawtooth+': '变形冰鲨的上锯齿',
    'Zamtrios Tailblade': '变形冰鲨的尾刃',
    'Zamtrios Tailbrand': '变形冰鲨的尾鳞',
    'Hyper Zamtrios Hide': '狞猛化变形冰鲨的皮',
    'Hyper Zamtrios Piel': '狞猛化变形冰鲨的厚皮',
    'Tiny Hermitaur Shell': '小盾蟹的甲壳',
    'Small Ceanataur Shell': '小镰蟹的甲壳',
    'Heavy Rustrazor Scalp': '铠裂将军镰蟹的重头壳',
    'Barroth Ridge+': '土砂龙的上棘',
    'Barroth Chine': '土砂龙的背脊',
    'Barroth Claw+': '土砂龙的尖爪',
    'Barroth Talon': '土砂龙的利爪',
    'Barroth Crown': '土砂龙的冠甲',
    'Fertile Mud': '肥沃泥块',
    'Uragaan Jaw': '爆锤龙的下颚',
    'Crystalbeard Maw': '宝缠爆锤龙的大口',
    'Crystalbeard Mandible': '宝缠爆锤龙的下颚',
    'Mystery Slime': '谜之粘菌',
    'Flashpoint Slime': '引爆点粘菌',
    'Duramboros Hump': '尾锤龙的驼峰',
    'Marbled Hump': '斑纹驼峰',
    'Durambolite': '尾锤龙石',
    'Khezu Special Cut': '电龙的特选皮',
    'Silverwind Blackpelage': '白疾风迅龙的黑色刚毛',
    'Zinogre Shocker+': '雷狼龙的上电毛',
    'Thunderlord Electrofur': '金雷公雷狼龙的电毛',
    'Thunderlord Boltfur': '金雷公雷狼龙的雷毛',
    'Thunderlord Horn+': '金雷公雷狼龙的尖角',
    'Thunderlord Gleamhorn': '金雷公雷狼龙的辉角',
    'Heavy Astalos Crest+': '电怪龙的重冠羽',
    'Heavy Boltreaver Shell': '青电主电怪龙的重壳',
    'Boltreaver Electric Barb': '青电主电怪龙的雷刺',
    'Elderfrost Trunkspine': '银岭雪狮子的躯干棘',
    'Soulseer Purplehide': '天眼泡狐龙的紫皮',
    'Grimclaw Talon': '荒钩爪轰龙的翼爪',
    'Grimclaw Talon+': '荒钩爪轰龙的尖翼爪',
    'Grimclaw Hardclaw': '荒钩爪轰龙的刚爪',
    'Twisted Horn': '弯曲的角',
    'Majestic Horn': '威武的角',
    'Diablos Hardhorn': '角龙的刚角',
    'Bloodbath Grimhorn': '鏖魔角龙的凶角',
    'Antinomic Wing': '矛盾之翼',
    'Contrary Scale': '相反鳞',
    'Diametrical Horn': '对立之角',
    'Defiled Scale': '污秽鳞',
    'S.Magala Prismwing+': '天廻龙的上虹翼',
    'S.Magala Caress+': '天廻龙的上抚鳞',
    'Black Blood': '黑血',
    'Akantor Shredtalon': '霸龙的裂爪',
    'Akantor Tallfang': '霸龙的长牙',
    'Akantor Greatfang': '霸龙的巨牙',
    'Ukanlos Shoveljaw': '崩龙的铲状下颚',
    'Ukanlos Shoveljaw+': '崩龙的上铲状下颚',
    'Broken Skypiercer': '破损的天穿',
    'Skypiercer': '天穿',
    'Skyswayer': '天降之引',
    'Dragon Healing Crystal': '龙愈晶',
    'Nakarkos Husk': '骸龙的骸',
    'Nakarkos Shell': '骸龙的甲壳',
    'Nakarkos Skull': '骸龙的头骨',
    'Nakarkos Vertebra': '骸龙的脊椎',
    'Radiant Mucus': '发光的粘液',
    'Radiant Mucus+': '发光的浓粘液',
    'Viscous Radiant Mucus': '黏稠的发光粘液',
    'Burned Husk': '焦黑的骸',
    'Golden Silk': '金色丝线',
    'Ahtal-Ka Purple Cocoon': '巨戟龙的紫茧',
    'Ahtal-Ka Foreblade': '巨戟龙的前刃',
    'Iridescent Carapace': '虹色甲壳',
    'Ahtal-Ka Pheromone': '巨戟龙的费洛蒙',
    'Ahtal-Ka Alluring Gem': '巨戟龙的诱引玉',
    'Dracophage Bug': '蚀龙虫',
    'Felyne Fur Ruby': '猫毛红玉',
    'Shocking Jelly': '电击凝胶',
    "Champion's Crest": '王者冠羽',
    'Glorious Crest': '伟大冠羽',
    'Redhelm Zenith Furyhair': '红盔青熊兽的天顶毛',
    'Snowbaron Plastron+': '大雪主白兔兽的上胸甲',
    'Splendid Beak': '华丽鸟喙',
    'Azurefeather+': '夜鸟的上鳞羽',
    'Malfestio Wingtalon+': '夜鸟的尖翼爪',
    'Hyper Azurefeather': '狞猛化夜鸟的鳞羽',
    'Nightcloak Plume': '胧隐夜鸟的羽毛',
    'Nightcloak Grandwing': '胧隐夜鸟的特上翼',
    'Nightcloak Clearscale': '胧隐夜鸟的澄鳞',
    'Sharpened Beak': '黑狼鸟的尖喙',
    'Bulldrome Hide+': '野猪王的上皮',
    'Bulldrome Thickhide': '野猪王的厚皮',
    'Dazzling Fluid': '耀眼体液',
    'Scalding Pleura+': '熔热胸甲+',
    'Scorching Pleura': '灼热胸甲',
    'Drilltusk Tusk': '岩穿鬼蛙的獠牙',
    'Drilltusk Tusk+': '岩穿鬼蛙的巨獠牙',
    'Drilltusk Gnawrl': '岩穿鬼蛙的磨牙',
    'Heart-stopping Beak': '绞蛇龙的惊骇喙',
    'Treasure Nugget': '宝缠爆锤龙的矿石碎片',
    'Large Treasure Nugget': '宝缠爆锤龙的大矿石碎片',
    'Brach Hammer': '碎龙的槌臂',
    'Brach Obliterator': '碎龙的灭杀臂',
    'Solar Bursa': '日光炎袋',
    'EZ Sonic Bomb': '补给专用音爆弹',
    'EZ Max Potion': '补给专用秘药',
    'EZ Barrel Bomb L': '补给专用大桶爆弹',
    'Anti-dragon Bomb': '对龙爆弹',
    'Training Guide': '超特训指南书',
    'Training Codex': '超特训秘传书',
    'Training Compendium': '超特训奥义书',
    'Felyne Codex': '猫的记忆秘传书',
    'Timeworn Ballista Shot': '古旧弩炮弹',
    'Cannon Ammo': '大炮弹',
    'Guild Flag': '公会旗帜',
    'Drome Coin': '速龙王币',
    'Horns Coin': '角龙币',
    'Lethal Kumori': '剧毒蜘蛛蝎',
    'Slickaxe': '炼金镐',
    'Rusted Fragment': '锈蚀碎片',
    'Ancient Fragment': '古代碎片',
    'Mythical Fragment': '传说碎片',
    'Sinister Cloth': '灾祸之布',
    'Sinister Darkcloth': '灾祸暗布',
    'Sinister Gloomcloth': '灾祸阴布',
    'Extravagant Artifact': '华丽遗物',
    'Opulent Artifact': '奢华遗物',
    'Decadent Artifact': '颓废遗物',
    'Broken Statue': '破损的雕像',
    'Large Broken Statue': '大型破损雕像',
    'Broken Cat God Statue': '破损的猫神像',
    'Doll Parts': '玩偶零件',
    'Weapon Codex': '武器秘典',
    'Bowgun Codex': '弩枪秘典',
    'Damaged Amber': '受损琥珀',
    'Cloudy Fragment': '浑浊碎片',
    'Strange Mask': '奇异面具',
    'Fluffy White Ball': '蓬松白色毛球',
    'Fluffy Black Ball': '蓬松黑色毛球',
    'Fusion Material - Head': '防具合成材·头部',
    'Fusion Material - Chest': '防具合成材·胸部',
    'Fusion Material - Arms': '防具合成材·腕部',
    'Fusion Material - Waist': '防具合成材·腰部',
    'Fusion Material - Legs': '防具合成材·腿部',
    'F Fusion Material - Head': '随从防具合成材·头部',
    'F Fusion Material - Chest': '随从防具合成材·身体',
    'Voucher': '兑换券',
    'Privilege': '特许券',
    'Privilege G': '特许券G',
    'Bistro Ticket G': '食堂券G',
    'VE Ticket': 'VE券',
    'VE Deluxe Ticket': 'VE高级券',
    'VE Bronze Ticket': 'VE铜券',
    'VE Silver Ticket': 'VE银券',
    'VE Golden Ticket': 'VE金券',
    'VE Cosmic Ticket': 'VE宇宙券',
    'Hyper Hunter I': '狞猛猎人之证I',
    'Hyper Hunter II': '狞猛猎人之证II',
    'Abyssal Mushroom': '深渊蘑菇',
    'Immortal Moth': '不死蛾',
    'Large Immortal Moth': '大不死蛾',
    'Round Acorn': '圆橡子',
    'Ancient Berry': '古代莓果',
    'Moofah Fur': '毛公兽毛皮',
    'Carnivore Egg': '肉食兽蛋',
    'Hyper Khezu Scrap': '狞猛化电龙的猛端材',
    'Hyper Khezu Scrap X': '狞猛化电龙的狞端材',
    'Hyper Astalos Scrap': '狞猛化电怪龙的猛端材',
    'Hyper Astalos Scrap X': '狞猛化电怪龙的狞端材',
    'Heavy G.Magala Scrap': '黑蚀龙的重端材',
    'Hyper G.Magala Scrap': '狞猛化黑蚀龙的猛端材',
    'Hyper G.Magala Scrap X': '狞猛化黑蚀龙的狞端材',
    'Heavy Chaotic Scrap': '混沌黑蚀龙的重端材',
    'Tomato Juice': '番茄汁',
    'Fairy Tail Mark': '妖精尾巴纹章',
    'F Pirate Coin J': 'F海盗J币',
    'Cardboard': '纸板',
    'Uniqlo Coin': '优衣库币',
    'Soulstone': '魂石',
    'Crows Coin': '乌鸦币',
    'Bicycle Club Application': '自行车部入部申请书',
    'Arena Ticket': '斗技券',
    'Grandpaw Coin': '爷爷币',
    'CoroCoro Ticket': '快乐快乐券',
    'Ushio Coin': '潮币',
    'Magi Coin': '魔笛币',
    'Pluto Stardust': '冥王星尘',
    'Roll of Fate': '命运之卷',
    'Pirate Ticket J': '海盗J券',
    'Famitsu Ticket': 'Fami通券',
    'Dengeki Ticket': '电击券',
    'Uniqlo Coin S': '优衣库币S',
    'Wind Waker': '风之杖',
    'Arwing Boarding Pass': '阿维恩搭乘券',
    'Super Mushroom': '超级蘑菇',
    'Design Pattern': '设计图样',
    'Triforce': '三角力量',
    'Samus Coin': '萨姆斯币',
    "Goddess's Grace": '女神的恩宠',
    "Goddess's Embrace": '女神的拥抱',
    'SF Coin': '街头霸王币',
    'Red Orb': '红之宝玉',
    'Ceratanium': '塞拉钛矿石',
    "Hero's Seal": '英雄之印',
    'Baby Journal': '婴儿日记',
    'Sunsnug Journal': '阳光日记',
    'Fan Club Newsletter': '粉丝俱乐部通讯',
    'Fan Club Application': '粉丝俱乐部申请书',
    'Fan Club Invite': '粉丝俱乐部邀请函',
    'Puppet Ticket': '人偶券',
    'Great Stone': '巨大之石',
    "Courier's Letter": '信使的信',
    'Kaioh Certificate': '海王证明书',
    'WORST Coin': 'WORST币',
    'Evidence': '证据',
    'Salaryman Coin': '上班族币',
    'Taisha-ryu Codex': '太社龙秘典',
    'Famitsu Coupon': 'Fami通优惠券',
    'Dengeki Ticket XX': '电击券XX',
    'Flying Xin Mark': '飞行信标',
    'Buccaneer Ticket J': '海盗J券',
    'Magic Realm Key': '魔法界之钥',
    'Zaruba Fragment': '扎鲁巴碎片',
    'Turnabout Ticket': '逆转券',
    'Navirou Ticket': '纳比露券',
    'F Spirit Stone': 'F灵魂石',
    'Club Promotion': '社团宣传单',
    'JDL Badge': 'JDL徽章',
    'Silver Crystal': '银水晶',
    'Zelda Ticket': '塞尔达券',
    'Zelda Ticket G': '塞尔达券G',
    'Sealing Shield': '封印之盾',
    'Option': '任选券',
    'Celestial Scroll': '天界卷轴',
    "Arthur's Armor": '亚瑟铠甲',
    'Zelda Ticket P': '塞尔达券P',
}

TERMINOLOGY_SOURCES = {
    'Butterfly Beetle': 'https://mhrise.mhrice.info/item.html',
    'Toxic Kumori': 'https://gamecat.fun/rise/zh/index.php?title=词典/日文检索',
    'Large Toxic Kumori': 'https://gamecat.fun/rise/zh/index.php?title=词典/日文检索',
    'Dracophage Bug': 'https://mhxx.kiranico.com/en/item/58779',
    'Felyne Fur Ruby': 'https://mhrise.mhrice.info/item/normal_0456.html',
    "Champion's Crest": 'https://mhxx.kiranico.com/en/item/509a8',
    'Glorious Crest': 'https://mhgu.kiranico.com/item/58a8d',
}

added = 0
for english, chinese in TRANSLATIONS.items():
    rows = db.execute("SELECT _id FROM items WHERE type='' AND name=?", (english,)).fetchall()
    if len(rows) != 1:
        raise SystemExit(f'Expected one item named {english!r}; found {len(rows)}')
    item_id = str(rows[0][0])
    current = linked.setdefault('items_by_id', {}).get(item_id)
    if current and current != english and any('\u4e00' <= c <= '\u9fff' for c in current):
        continue
    linked['items_by_id'][item_id] = chinese
    source = {
        'name': chinese,
        'english': english,
        'method': 'project-reviewed translation of the complete MHGenDatabase English item name using the item-part and monster terminology glossary',
    }
    if english in TERMINOLOGY_SOURCES:
        source['source'] = TERMINOLOGY_SOURCES[english]
        source['method'] = 'project-reviewed item translation checked against the cited MHXX multi-language item term'
    sources.setdefault('items', {})[item_id] = [source]
    added += 1

linked_path.write_text(json.dumps(linked, ensure_ascii=False, indent=2) + '\n')
sources_path.write_text(json.dumps(sources, ensure_ascii=False, indent=2) + '\n')
print(f'Imported {added} reviewed item-name translations.')
